homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.home, name='home'),
    path('hobi/', views.hobi, name='hobi'),
    path('hubungi/', views.hubungi, name = 'hubungi'),
    path('pendidikan/', views.pendidikan, name = 'pendidikan'),
    path('Schedule/', views.Join, name = 'schedule') ,
    path('<int:pk>', views.sched_delete, name = 'delete'),
    path('signup/',views.signup, name ='signup'),
    path('signin/',views.signin, name ='signin'),
    path('logout/',views.logout1, name ='logout'),
    path('caribuku/',views.books,name='books'),
]

story/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
]

homepage/models.py
from django.db import models

# Create your models here.
class Schedule(models.Model) :
    Mata_Kuliah = models.CharField(max_length = 50,default='')
    Dosen = models.CharField(max_length = 50,default='')
    Kelas = models.CharField(max_length = 50,default='')
    Tahun = models.IntegerField()
    SKS = models.IntegerField()

homepage/forms.py
from django import forms

class SchedForm(forms.Form) :
    Mata_Kuliah = forms.CharField(widget = forms.TextInput(attrs = {
        'class' : 'form-control' ,
        'placeholder' : 'Mata_Kuliah' ,
        'type' : 'text',
        'required' : True ,
    }))

    Dosen = forms.CharField(widget = forms.TextInput(attrs = {
        'class' : 'form-control' ,
        'placeholder' : 'Dosen' ,
        'type' : 'text',
        'required' : True ,
    }))
    
    Kelas = forms.CharField(widget = forms.TextInput(attrs = {
        'class' : 'form-control' ,
        'placeholder' : 'Kelas' ,
        'type' : 'text',
        'required' : True ,
    }))

    Tahun = forms.IntegerField(widget = forms.NumberInput(attrs = {
        'class' : 'form-control' ,
        'placeholder' : 'yyyy' ,
        'type' : 'number',
        'required' : True ,
    }))

    SKS = forms.IntegerField(widget = forms.NumberInput(attrs = {
        'class' : 'form-control' ,
        'placeholder' : 'SKS' ,
        'type' : 'number',
        'required' : True ,
    }))

homepage/views.py
from django.shortcuts import render, redirect
from .models import Schedule as jadwal
from .forms import SchedForm
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout

# Create your views here.
def home(request):
    return render(request, 'home.html')

def hobi(request):
    return render(request, 'hobi.html')

def hubungi(request):
    return render(request, 'hubungi.html')

def pendidikan(request):
    return render(request, 'pendidikan.html')

def Join(request) :
    if request.method == "POST" :
        form = SchedForm(request.POST)
        if form.is_valid() :
            sched = jadwal()
            sched.Mata_Kuliah = form.cleaned_data['Mata_Kuliah']
            sched.Dosen = form.cleaned_data['Dosen']
            sched.Kelas = form.cleaned_data['Kelas']
            sched.Tahun = form.cleaned_data['Tahun']
            sched.SKS = form.cleaned_data['SKS']
            sched.save()
        return redirect('/Schedule')
    else :
        sched = jadwal.objects.all()
        form = SchedForm()
        response = {'sched' : sched , 'form' : form}
        return render(request, 'schedule.html', response)

def sched_delete(request, pk) :
    if request.method == "POST" :
        form = SchedForm(request.POST)
        if form.is_valid() :
            sched = jadwal()
            sched.Mata_Kuliah = form.cleaned_data['Mata_Kuliah']
            sched.Dosen = form.cleaned_data['Dosen']
            sched.Kelas = form.cleaned_data['Kelas']
            sched.Tahun = form.cleaned_data['Tahun']
            sched.SKS = form.cleaned_data['SKS']
            sched.save()
        return redirect('/Schedule')
    else :
        sched = jadwal.objects.filter(pk=pk).delete()
        data = jadwal.objects.all()
        form = SchedForm()
        response = {'sched' : data , 'form' : form}
        return render(request, 'schedule.html', response)

def signup(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = User.objects.create_user(username = username , password = password)
        return redirect('/signup')
    else :
        return render(request,'signup.html')

def signin(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username = username , password = password)
        if user != None :
            login(request,user)
            
            return redirect('/home')
        else :
            return redirect('/signin')
    else :
        return render(request,'signin.html')
    
def logout1(request):
    logout(request)
    return redirect('/logout')

def books(request):
    return render(request,'caribuku.html')

homepage/templates/caribuku.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<title>biodata Rasendrio</title>
	<!-- file CSS -->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
	<link href='https://fonts.googleapis.com/css?family=Bree Serif' rel='stylesheet'>
	<link rel="stylesheet" type="text/css" href="{% static 'main.css' %}">
	<link href='https://fonts.googleapis.com/css?family=Bree Serif' rel='stylesheet'>

	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	<!-- JS, Popper.js, and jQuery -->
	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
	<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
	<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>
	<script src="{% static 'accordion.js' %}"></script>
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</head>
<body>
	<!-- navbar -->
	<ul>
        <li><a href="{% url 'homepage:home' %}">Halo! {{ user }}</a></li>
        <li><a class="active" href="{% url 'homepage:home' %}">Home</a></li>
        <li><a href="{% url 'homepage:hobi' %}">Hobi dan Ketertarikan</a></li>
        <li><a href="{% url 'homepage:pendidikan' %}">Riwayat Pendidikan</a></li>
        <li><a href="{% url 'homepage:hubungi' %}">Hubungi Saya</a></li>
        <li><a href="{% url 'homepage:schedule' %}">Jadwal Kuliah</a></li>
        <li><a href="{% url 'homepage:books' %}">Books</a></li>
        <li><a href="{% url 'homepage:signup' %}">Signup</a></li>
		<li><a href="{% url 'homepage:signin' %}">Signin</a></li>
		<li><a href="{% url 'homepage:logout' %}">Logout</a></li>
	</ul>

    
    <div class="container">
        <input type="text" id="searchinput">
        <button id="searchbutton">
            Search
        </button>
        <table>
            <thead>
               <tr>
                   <th>
                       Title
                   </th>
                   <th>
                        Authors
                   </th>
                   <th>
                        Publisher
                   </th>
                   <th>
                        Publish date
                   </th>
               </tr> 
            </thead>
            <tbody id="tablebooks">

            </tbody>
        </table>
    </div>
    <script src="{% static 'books.js' %}"></script>
</body>
</html>

homepage/templates/hobi.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<title>biodata Rasendrio</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
	<link href='https://fonts.googleapis.com/css?family=Bree Serif' rel='stylesheet'>
	<link rel="stylesheet" type="text/css" href="{% static 'main.css' %}">
	<link href='https://fonts.googleapis.com/css?family=Bree Serif' rel='stylesheet'>

	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	<!-- JS, Popper.js, and jQuery -->
	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</head>
<body>
	<!-- navbar -->
	<ul>
		<li><a href="{% url 'homepage:home' %}">Halo! {{ user }}</a></li>
		<li><a class="active" href="{% url 'homepage:home' %}">Home</a></li>
		<li><a href="{% url 'homepage:hobi' %}">Hobi dan Ketertarikan</a></li>
		<li><a href="{% url 'homepage:pendidikan' %}">Riwayat Pendidikan</a></li>
		<li><a href="{% url 'homepage:hubungi' %}">Hubungi Saya</a></li>
		<li><a href="{% url 'homepage:schedule' %}">Jadwal Kuliah</a></li>
		<li><a href="{% url 'homepage:books' %}">Books</a></li>
		<li><a href="{% url 'homepage:signup' %}">Signup</a></li>
		<li><a href="{% url 'homepage:signin' %}">Signin</a></li>
		<li><a href="{% url 'homepage:logout' %}">Logout</a></li>
	</ul>

	<div class="section1" id="hobipage">
		<div class="container">
			<div class="row " style="padding-bottom: 15em">
				<div class="col-md-4" style="text-align: center;">
					<img class="rounded-circle hover" src="{% static './images/saxo1.jpg' %}" style="width:100%;height: 50%;margin-top: 2em">
					<span class="white" style="margin-top: 2em; font-size: 20px">Saya senang bermain musik, karena seperti di deskripsi diri saya , saya menyebutkan bahwa saya memiliki pembawaan yang santai, karena menurut saya dengan bermusik kita dapat lebih tenang dan santai. Saya sangat suka bermain alat musik disaat saya sedang banyak pikiran. Alat musik yang sering saya mainkan adalah saxophone.</span>
				</div>
				<div class="col-md-4" style="text-align: center">
					<img class="rounded-circle hover" src="{% static './images/swim.jpg' %}" style="width: 100%;height: 50%;margin-top: 2em" >
					<span class="white" style="margin-top: 2em; font-size: 20px">Saya juga senang berolahraga, karena menurut saya dengan berolahraga kita dapat menghilangkan aura negatif dalam diri kita. Kita juga bisa mendapatkan pelajaran bersaing dengan sportif di olahraga. Saya suka beberapa olahraga, seperti futsal, bulutangkis dan juga renang. Namun dari semua itu saya paling suka renang karena menurut saya renang adalah olahraga yang paling bermanfaat, baik untuk pernafasan maupun fisik. Saya juga telah memperoleh beberapa prestasi dari renang.</span>
				</div>
				<div class="col-md-4" style="text-align: center">
					<img class="rounded-circle hover" src="{% static './images/bisnis.jpg' %}" style="width:100%;height: 50%;margin-top: 2em">
					<span class="white" style="margin-top: 2em; font-size: 20px">Tidak lama ini saya baru terjun ke dunia ini. Yap, itu bisnis. Saya tertarik akan ini karena kita dapat memperluas wawasan serta koneksi kita untuk masa depan. Kita juga dapat belajar untuk menjadi pemimpin. Dengan wawasan, pengalaman serta koneksi disini kita akan siap untuk melewati hidup kita di masa depan dan akan bermanfaat bagi banyak orang.</span>
				</div>
			</div>
		</div>
	</div>

</body>
</html>

homepage/templates/home.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<title>biodata Rasendrio</title>
	<!-- file CSS -->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
	<link href='https://fonts.googleapis.com/css?family=Bree Serif' rel='stylesheet'>
	<link rel="stylesheet" type="text/css" href="{% static 'main.css' %}">
	<link href='https://fonts.googleapis.com/css?family=Bree Serif' rel='stylesheet'>

	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	<!-- JS, Popper.js, and jQuery -->
	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
	<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
	<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>
	<script src="{% static 'accordion.js' %}"></script>
</head>
<body>
	<!-- navbar -->
	<ul>
		<li><a href="{% url 'homepage:home' %}">Halo! {{ user }}</a></li>
		<li><a class="active" href="{% url 'homepage:home' %}">Home</a></li>
		<li><a href="{% url 'homepage:hobi' %}">Hobi dan Ketertarikan</a></li>
		<li><a href="{% url 'homepage:pendidikan' %}">Riwayat Pendidikan</a></li>
		<li><a href="{% url 'homepage:hubungi' %}">Hubungi Saya</a></li>
		<li><a href="{% url 'homepage:schedule' %}">Jadwal Kuliah</a></li>
		<li><a href="{% url 'homepage:books' %}">Books</a></li>
		<li><a href="{% url 'homepage:signup' %}">Signup</a></li>
		<li><a href="{% url 'homepage:signin' %}">Signin</a></li>
		<li><a href="{% url 'homepage:logout' %}">Logout</a></li>
	</ul>

	<div class="section1">
		<div class="row">
			<div class="col-md-12">
				<div class="row" style="margin: 5em 10em;">
					<div class="col-md-4">
						<img class="hover" src="{% static './images/foto1.jpg' %}" style="margin-top: 2em">
					</div>
					<div class="col-md-8 wrap hover">
						<h1 >Hai!</h1>
						<h2 >Saya Rasendrio Muhammad</h2>
						<h4 style="margin-top: 1em">1906303084</h4>
						<h4 style="margin-top: 5em"> Perkenalkan saya mahasiswa dari Fakultas Ilmu Komputer Universitas Indonesia angkatan 2019. Saya pribadi tertarik akan suatu hal yang baru dan akan mudah beradaptasi dengan lingkungan baru tersebut. Saya juga orang yang memiliki pembawaan yang santai dalam setiap kondisi.</h4>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div id="accordion">
		<div class="accitem">
			<h3>Deskripsi</h3>
			<button onclick="return move(this,1)">V</button>
			<button onclick="return move(this,-1)">^</button>
		</div>
		<div>
		  <p>
			  Web yang saya buat merupakan biodata diri saya yang merupakan tugas story dari Mata Kuliah PPW
		  </p>
		</div>
		<div class="accitem">
			<h3>Aktifitas</h3>
			<button onclick="return move(this,1)">V</button>
			<button onclick="return move(this,-1)">^</button>
		</div>
		<div>
		  <p>
			  Belajar di Fasilkom serta menjalani bisnis
		  </p>
		</div>
		<div class="accitem">
			<h3>Organisasi</h3>
			<button onclick="return move(this,1)">V</button>
			<button onclick="return move(this,-1)">^</button>
		</div>
		<div>
		  <p>
			  Perak Fasilkom
			  OSIS
		  </p>
		</div>
		<div class="accitem">
			<h3>Penghargaan</h3>
			<button onclick="return move(this,1)">V</button>
			<button onclick="return move(this,-1)">^</button>
		</div>
		<div>
		  <p>
			  Juara 2 Show Competition(alat tiup), Kerkrade, Netherlands
			  Juara 3 02SN cabang renang tingkat Jakarta Selatan
		  </p>
		</div>
	</div>
</body>
</html>

homepage/templates/hubungi.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<title>biodata Rasendrio</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
	<link href='https://fonts.googleapis.com/css?family=Bree Serif' rel='stylesheet'>
	<link rel="stylesheet" type="text/css" href="{% static 'main.css' %}">
	<link href='https://fonts.googleapis.com/css?family=Bree Serif' rel='stylesheet'>

	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	<!-- JS, Popper.js, and jQuery -->
	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</head>
<body>
	<!-- navbar -->
	<ul>
		<li><a href="{% url 'homepage:home' %}">Halo! {{ user }}</a></li>
		<li><a class="active" href="{% url 'homepage:home' %}">Home</a></li>
		<li><a href="{% url 'homepage:hobi' %}">Hobi dan Ketertarikan</a></li>
		<li><a href="{% url 'homepage:pendidikan' %}">Riwayat Pendidikan</a></li>
		<li><a href="{% url 'homepage:hubungi' %}">Hubungi Saya</a></li>
		<li><a href="{% url 'homepage:schedule' %}">Jadwal Kuliah</a></li>
		<li><a href="{% url 'homepage:books' %}">Books</a></li>
		<li><a href="{% url 'homepage:signup' %}">Signup</a></li>
		<li><a href="{% url 'homepage:signin' %}">Signin</a></li>
		<li><a href="{% url 'homepage:logout' %}">Logout</a></li>
	</ul>

	<div class="section1" id="hobipage">
		<div class="container">
			<div class="row " style="padding-bottom: 15em ; padding-top: 5em;">
				<div class="col-md-6" style="text-align: center;">
					<a href = "https://wa.me/6282111116323">
						<img class="rounded-circle hover" src="{% static './images/wa.png' %}" style="width:85%;height: 85%;margin-top: 2em">
					</a>
					<span class="white" style="margin-top: 2em; font-size: 25px">Whatsapp</span>
				</div>
				<div class="col-md-6" style="text-align: center">
					<a href = "https://www.instagram.com/rasendrio/">
						<img class="rounded-circle hover" src="{% static './images/instagram.png' %}" style="width:85%;height: 85%;margin-top: 2em">
					</a>
					<span class="white" style="margin-top: 2em; font-size: 25px">Instagram</span>
				</div>
			</div>
		</div>
	</div>

</body>
</html>

homepage/templates/schedule.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<title>biodata Rasendrio</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
	<link href='https://fonts.googleapis.com/css?family=Bree Serif' rel='stylesheet'>
	<link rel="stylesheet" type="text/css" href="{% static 'main.css' %}">
	<link href='https://fonts.googleapis.com/css?family=Bree Serif' rel='stylesheet'>

	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	<!-- JS, Popper.js, and jQuery -->
	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</head>
<body>
    <!-- navbar -->
    <ul>
        <li><a href="{% url 'homepage:home' %}">Halo! {{ user }}</a></li>
        <li><a class="active" href="{% url 'homepage:home' %}">Home</a></li>
        <li><a href="{% url 'homepage:hobi' %}">Hobi dan Ketertarikan</a></li>
        <li><a href="{% url 'homepage:pendidikan' %}">Riwayat Pendidikan</a></li>
        <li><a href="{% url 'homepage:hubungi' %}">Hubungi Saya</a></li>
        <li><a href="{% url 'homepage:schedule' %}">Jadwal Kuliah</a></li>
        <li><a href="{% url 'homepage:books' %}">Books</a></li>
        <li><a href="{% url 'homepage:signup' %}">Signup</a></li>
		<li><a href="{% url 'homepage:signin' %}">Signin</a></li>
		<li><a href="{% url 'homepage:logout' %}">Logout</a></li>
    </ul>

    <form action='' method="POST">
        {% csrf_token %}
        {{form}}
        <div class="centre-items">
            <input type="submit" class="btn btn-primary" value="Add schedule">
        </div>
    </form>

    <table class="table">
        <thead>
            <tr>
            <th scope="col">Mata_Kuliah</th>
            <th scope="col">Dosen</th>
            <th scope="col">Kelas</th>
            <th scope="col">Tahun</th>
            <th scope="col">SKS</th>
            </tr>
        </thead>
        <tbody>
            {% for jadwal in sched %}
                <tr>
                <th scope="row">{{jadwal.Mata_Kuliah}}</th>
                <td>{{jadwal.Dosen}}</td>
                <td>{{jadwal.Kelas}}</td>
                <td>{{jadwal.Tahun}}</td>
                <td>{{jadwal.SKS}}</td>
                <td><a href="{% url 'homepage:delete' pk=jadwal.pk %}"><button class="btn btn-icon btn-danger"></button></a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

</body>
</html>